### PR TITLE
allow any extension

### PR DESCRIPTION
**Pull request by dfliess**
Accepts a extPattern option, keep .js as default

### CODE REVIEW

**Comment by francisek** [comment]
Great, your feature makes sense.
Could you write the related unit tests in the all() method with custom extension (say `\\.txt`) and with regex pattern extension ( `\\.(txt|js)`). That would be great.

Thx

**Comment by dfliess** [comment]
I've added also a test on the getPaths to show that when you have multiple files will return one choosing it alphabetically by extension.

**Comment by francisek** [comment]
Looks like you misses the fixture files to pass the tests.

**Comment by dfliess** [comment]
Sorry! I've just added.

**Pull request closed without merging**
